import type { technologies } from "../content/config";

export const colors: Record<(typeof technologies)[number], string> = {
  javascript: "bg-[#f7df1e] text-black",
  typescript: "bg-[#3178c6] text-white",
  wordpress: "bg-[#21759b] text-white",
  react: "bg-[#61dafb] text-black",
  node: "bg-[#339933] text-white",
  php: "bg-[#777bb4] text-white",
  html: "bg-[#e34f26] text-white",
  css: "bg-[#1572b6] text-white",
  express: "bg-[#000000] text-white",
  tailwind: "bg-[#38b2ac] text-white",
  graphql: "bg-[#e10098] text-white",
  mongodb: "bg-[#47a248] text-white",
  postgres: "bg-[#336791] text-white",
  mysql: "bg-[#00758f] text-white",
  firebase: "bg-[#ffca28] text-black",
  aws: "bg-[#ff9900] text-black",
  docker: "bg-[#2496ed] text-white",
  astro: "bg-[#ff5a03] text-white",
  alpinejs: "bg-[#8bc0d0] text-black",
  angular: "bg-[#dd0031] text-white",
  apollo: "bg-[#311c87] text-white",
  deno: "bg-[#000000] text-white",
  fastify: "bg-[#202020] text-white",
  nextjs: "bg-[#000000] text-white",
  nuxt: "bg-[#00c58e] text-white",
  sapper: "bg-[#ff3e00] text-white",
  svelte: "bg-[#ff3e00] text-white",
  vue: "bg-[#42b883] text-white",
  nestjs: "bg-[#ea2845] text-white",
} as const;

export const names: Record<(typeof technologies)[number], string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  wordpress: "WordPress",
  react: "React",
  node: "Node.js",
  php: "PHP",
  html: "HTML",
  css: "CSS",
  express: "Express",
  tailwind: "Tailwind CSS",
  graphql: "GraphQL",
  mongodb: "MongoDB",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  firebase: "Firebase",
  aws: "AWS",
  docker: "Docker",
  astro: "Astro",
  alpinejs: "Alpine.js",
  angular: "Angular",
  apollo: "Apollo",
  deno: "Deno",
  fastify: "Fastify",
  nextjs: "Next.js",
  nuxt: "Nuxt.js",
  sapper: "Sapper",
  svelte: "Svelte",
  vue: "Vue.js",
  nestjs: "NestJS",
} as const;
